---
title: "RachelStratemeier_MSDS6306_HW4"
author: "Rachel Stratemeier"
date: "5/29/2019"
output: 
  html_document:
    keep_md: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup_2}
sessionInfo()

library(rvest)
library(stringr)
library(dplyr)
library(ggplot2)
```

# Question 1: Harry Potter Scraping
First, get the table in a data frame.
```{r get_hp_data}
url <- 'https://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1'
hp_raw <- read_html(url)
hp_data <- html_node(hp_raw, ".cast_list")
hp_table <- html_table(hp_data)
str(hp_table)
```
Next, clean the data.
```{r clean_hp_data}
harry <- hp_table[, c(2, 4)]
names(harry) <- c("Firstname", "Character")
harry$Character[11] <- "Griphook / Professor Filius Flitwick"
harry$Character <- gsub(" \\n ", "", harry$Character)
harry_clean <- harry[-c(1,93),]
harry_clean$Surname <- word(harry_clean$Firstname, -1)
harry_clean$Firstname <- gsub("\\s*\\w*$", "", harry_clean$Firstname)
harry_clean <- harry_clean[,c("Firstname", "Surname", "Character")]
head(harry_clean, 10)
```

# Question 2: ESPN Scraping
First, obtain the data.
```{r get_espn_data}
spurs_url <- "http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs"
spurs_raw <- read_html(spurs_url)
spurs_data_1 <- html_node(spurs_raw, ".Table2__right-aligned.Table2__table-fixed.Table2__Table--fixed--left.Table2__table")
spurs_table_1 <- html_table(spurs_data_1)
spurs_data_2 <- html_nodes(spurs_raw, "table")
spurs_data_2_2 <- html_nodes(spurs_data_2, "table")
spurs_data_3 <- html_table(spurs_data_2_2[6])
spurs_table_2 <- data.frame(spurs_data_3)
spurs_table_2 <- spurs_table_2 %>% mutate(id = row_number())
spurs_table_1 <- spurs_table_1 %>% mutate(id = row_number())
spurs <- merge(spurs_table_1, spurs_table_2)
```
Now, clean up the data.
```{r clean_espn}
spurs$Position <- word(spurs$Name, -1)
spurs$Name <- gsub("\\s*\\w*$", "", spurs$Name)
spurs <- spurs[1:13,c(2,17,3:16)]
```
Finally, make the bar chart.
```{r espn_plot}
ggplot(spurs, aes(x=Name, y=FG., fill=as.factor(Position))) + geom_bar(stat='identity') + coord_flip() + labs(y="Field Goals Percentage", x="Player") + ggtitle("Spurs Players Field Goals per Game")
```

